spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.30.216.145:5432/sampledb
    username: openshiftuser
    password: openshiftpass
  mongodb:
    host: localhost
    port: 27017
    authenticationDatabase: admin
    username: openshiftmongo
    password: openshiftpass
    database: sampledb
  activemq:
    brokerUrl: tcp://172.17.0.13:5672
    user: admin
    password: admin
    packages.trust-all: true


  #    openshiftpassadmin
#  Username: openshiftmongo
#  Password: openshiftpass
#  Database Name: sampledb
#  Connection URL: mongodb://openshiftmongo:openshiftpass@mongodb/sampledb
