spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.30.216.145:5432/sampledb
    username: openshiftuser
    password: openshiftpass
  mongodb:
    host: localhost
    port: 27017
    authenticationDatabase: admin
    username: openshiftmongo
    password: openshiftpass
    database: sampledb
  activemq:
#    brokerUrl: tcp://broker123-amq-tcp-first-redhat-proj.192.168.99.105.nip.io:443
    brokerUrl: tcp://172.30.46.159:61616
    user: userQ5D
    password: t57Ahv6V
    packages.trust-all: true


  #    openshiftpassadmin
#  Username: openshiftmongo
#  Password: openshiftpass
#  Database Name: sampledb
#  Connection URL: mongodb://openshiftmongo:openshiftpass@mongodb/sampledb
